version: '3'
services:
  app:
    container_name: 'rev_proxy_npm'
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /home/admin/docker-data/ngnix-proxy-manager:/data
networks:
  default:
    external:
      name: public